[package]
name = "Subchunker"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
slint = "1.14.1"
sysinfo = "0.37.2"
os_info = "3.14.0"
rust-gpu-tools = { version = "0.7.2", features = ["opencl"], default-features = false }

[build-dependencies]
slint-build = "1.14.1"